#!/usr/bin/env python
"""Build the full CoEval paper deploy bundle from index.html.

Run from anywhere:  python docs/paper/build_paper.py

Produces in docs/paper/:
  - CoEval.docx            (1-col, camera-ready-generic)   [committed, deployed]
  - CoEval_twocolumn.docx  (2-col, two-column)             [committed, deployed]
  - index.review.html      (local annotatable review copy) [gitignored, machine-local]

And it:
  - verifies EVERY figure embeds in both docx (build-artifact canary; fails loudly);
  - asserts both Word download links are present in index.html;
  - registers docs/paper as an html2anno served root, so the deployed paper's
    "Annotate (local)" link (http://127.0.0.1:7800/serve/coeval/index.review.html)
    resolves to the local review copy;
  - ensures index.review.html and .annotations/ are gitignored.

The review copy carries <meta name="anno-version"> (rolls the annotation cycle on
content change), <meta name="anno-path"> (its canonical disk path, so file:// and the
http://localhost-served view share one .annotations/ store), and the annotate.js
include. It is intentionally NOT committed: it embeds a machine-specific absolute path
and a localhost script, and is regenerated by this script.
"""
from __future__ import annotations
import hashlib
import json
import os
import re
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = Path(os.environ.get("HTML2DOC_SKILL", r"C:/Users/apart/.claude/skills/html2doc"))
SRC = HERE / "index.html"
MML = HERE / "_mathml.html"
ROOT_ID = "coeval"
SERVICE = "http://127.0.0.1:7800"


def _run(cmd, **kw):
    subprocess.run(cmd, check=True, **kw)


def build_mathml():
    env = dict(os.environ, NODE_PATH=str(SKILL / "node_modules"))
    _run(["node", str(SKILL / "scripts/katex_to_mathml.js"),
          "--input", str(SRC), "--output", str(MML)], env=env)


def build_docx(profile, out_name):
    out = HERE / out_name
    raw = HERE / ("_raw_%s.docx" % profile)
    _run([sys.executable, str(SKILL / "scripts/convert_to_docx.py"),
          "--input", str(MML), "--output", str(raw), "--profile", profile])
    _run([sys.executable, str(SKILL / "scripts/apply_academic_style.py"),
          "--input", str(raw), "--output", str(out), "--profile", profile])
    raw.unlink(missing_ok=True)
    return out


def n_figs_in_html():
    return len(re.findall(r"<img\b", SRC.read_text(encoding="utf-8")))


def verify_figs(docx):
    with zipfile.ZipFile(docx) as z:
        got = sum(1 for n in z.namelist() if n.startswith("word/media/"))
    want = n_figs_in_html()
    if got != want:
        raise SystemExit("  FIGURE CHECK FAILED in %s: %d embedded / %d in source"
                         % (docx.name, got, want))
    print("  figures: %d/%d embedded in %s" % (got, want, docx.name))


def assert_links():
    html = SRC.read_text(encoding="utf-8")
    for href in ("CoEval.docx", "CoEval_twocolumn.docx"):
        if ('href="%s"' % href) not in html:
            raise SystemExit("  LINK CHECK FAILED: %s not linked in index.html" % href)
    print("  both Word download links present in index.html")


def build_review():
    html = SRC.read_text(encoding="utf-8")
    ver = "c-" + hashlib.sha1(html.encode("utf-8")).hexdigest()[:8]
    # Drop the Word download links from the review copy (they stay in the deployed
    # index.html). They are deploy chrome, irrelevant while annotating.
    html = re.sub(r'[ \t]*<a\b[^>]*href="CoEval(?:_twocolumn)?\.docx"[^>]*>.*?</a>\n?',
                  '', html)
    review = HERE / "index.review.html"
    anno_path = str(review).replace("\\", "/")
    meta = ('<meta name="anno-version" content="%s">\n  '
            '<meta name="anno-path" content="%s">\n' % (ver, anno_path))
    if re.search(r"<head[^>]*>", html):
        html = re.sub(r"(<head[^>]*>)", r"\1\n  " + meta, html, count=1)
    else:
        html = meta + html
    include = '<script src="http://127.0.0.1:7800/annotate.js"></script>\n'
    html = (html.replace("</body>", include + "</body>", 1)
            if "</body>" in html else html + include)
    review.write_text(html, encoding="utf-8")
    print("  wrote %s (anno-version %s)" % (review.name, ver))


def register_root():
    body = json.dumps({"id": ROOT_ID, "dir": str(HERE)}).encode("utf-8")
    try:
        req = urllib.request.Request(SERVICE + "/api/register-root", data=body,
                                     headers={"Content-Type": "application/json"})
        r = json.load(urllib.request.urlopen(req, timeout=3))
        print("  registered served root via service: %s -> %s" % (r.get("id"), r.get("dir")))
    except Exception:
        sr = Path(os.path.expanduser("~")) / ".html2anno" / "served_roots.json"
        roots = {}
        if sr.exists():
            try:
                roots = json.loads(sr.read_text(encoding="utf-8")).get("roots", {})
            except Exception:
                roots = {}
        roots[ROOT_ID] = str(HERE)
        sr.parent.mkdir(parents=True, exist_ok=True)
        sr.write_text(json.dumps({"roots": roots}, indent=2), encoding="utf-8")
        print("  service down; wrote served root directly to %s" % sr)


def ensure_gitignore():
    gi = None
    p = HERE
    for _ in range(6):
        if (p / ".git").exists():
            gi = p / ".gitignore"
            break
        p = p.parent
    if gi is None:
        gi = HERE.parents[2] / ".gitignore"
    text = gi.read_text(encoding="utf-8") if gi.exists() else ""
    want = ["docs/paper/index.review.html", ".annotations/"]
    add = [w for w in want if w not in text]
    if add:
        with open(gi, "a", encoding="utf-8") as fh:
            if text and not text.endswith("\n"):
                fh.write("\n")
            fh.write("\n# html2anno local review artifacts\n" + "\n".join(add) + "\n")
        print("  gitignored: %s" % ", ".join(add))
    else:
        print("  review artifacts already gitignored")


def main():
    print("Building CoEval paper bundle from index.html ...")
    build_mathml()
    print("1-col docx:")
    verify_figs(build_docx("camera-ready-generic", "CoEval.docx"))
    print("2-col docx:")
    verify_figs(build_docx("two-column", "CoEval_twocolumn.docx"))
    print("links:")
    assert_links()
    print("review HTML:")
    build_review()
    print("served root:")
    register_root()
    print("gitignore:")
    ensure_gitignore()
    MML.unlink(missing_ok=True)
    print("DONE - both docx (figures verified), index.review.html, served root, gitignore.")


if __name__ == "__main__":
    main()
